import React,{useState,useEffect} from 'react';import{createRoot}from'react-dom/client';
import{cents,metrics,filterRows,fingerprint,validate,previousPeriod}from'./domain';import{readExcel,convert}from'./importer';import{db,listExpenses,saveExpenses,removeExpenses}from'./backend';import'./style.css';
const euro=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format((n||0)/100);
const today=new Date().toLocaleDateString('en-CA');const year=new Date().getFullYear();
const demo=[{id:'demo1',date:`${year}-01-05`,description:'Affitto · esempio',amount:-80000,person:'Peng',account:'Conto personale',category:'Affitto',shared:true,kind:'expense'},{id:'demo2',date:`${year}-01-02`,description:'Stipendio · esempio',amount:220000,person:'Peng',account:'Conto personale',category:'Stipendio',shared:false,kind:'income'}];
function App(){
 const[rows,setRows]=useState(demo),[tab,setTab]=useState('Metriche'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[session,setSession]=useState(null);
 const[f,setF]=useState({from:`${year}-01-01`,to:`${year}-12-31`,person:'',account:'',category:'',scope:''});
 const[sheets,setSheets]=useState([]),[sheet,setSheet]=useState(0),[map,setMap]=useState({date:2,description:4,amount:5,person:0,account:3,category:6,shared:7}),[preview,setPreview]=useState(null),[chosen,setChosen]=useState(new Set()),[defaults,setDefaults]=useState({person:'Peng',account:'Conto personale'});
 const[form,setForm]=useState({date:today,description:'',amount:'',person:'Peng',account:'Conto personale',category:'Varie',shared:false,kind:'expense'});
 useEffect(()=>{if(!db)return;db.auth.getSession().then(({data})=>setSession(data.session));const{data}=db.auth.onAuthStateChange((_,s)=>setSession(s));return()=>data.subscription.unsubscribe();},[]);
 useEffect(()=>{if(db){setRows([]);if(session)listExpenses().then(setRows).catch(e=>setMessage(e.message));}},[session]);
 const run=async fn=>{setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e.message);}finally{setBusy(false);}};
 const persist=async added=>{if(db)await saveExpenses(added);setRows(r=>[...r.filter(x=>!added.some(a=>a.id===x.id)),...added]);};
 const comparison=previousPeriod(f.from,f.to),rangeValid=!!comparison.from; const filtered=filterRows(rows,f),m=metrics(filtered),prev=metrics(filterRows(rows,{...f,...comparison}));
 const pick=(k,v)=>setF({...f,[k]:v});const unique=k=>[...new Set(rows.map(r=>r[k]))].sort();
 const select=(label,key)=> <label>{label}<select aria-label={label} value={f[key]} onChange={e=>pick(key,e.target.value)}><option value="">Tutti</option>{unique(key).map(v=><option key={v}>{v}</option>)}</select></label>;
 async function upload(file){if(!file)return;await run(async()=>{setSheets(await readExcel(file));setSheet(0);setPreview(null);});}
 function prepare(){const p=convert(sheets[sheet].rows,map,defaults);const known=new Set(rows.map(fingerprint));const seen=new Set();p.result=p.result.map(r=>{const key=fingerprint(r),duplicate=known.has(key)||seen.has(key);seen.add(key);return{...r,duplicate};});setPreview(p);setChosen(new Set(p.result.filter(r=>!r.duplicate).map(r=>r.id)));}
 if(db&&!session)return <main className="login"><h1>Note Spese</h1><p>Accedi allo spazio condiviso.</p><form onSubmit={e=>{e.preventDefault();const fd=new FormData(e.target);run(async()=>{const{error}=await db.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error)throw error;});}}><label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><button disabled={busy}>Accedi</button></form><p role="status">{message}</p></main>;
 return <><aside><div className="brand">N<span>Note Spese</span></div><nav>{['Metriche','Movimenti','Importa','Aggiungi'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</nav><small>Peng & Sofi</small>{db&&<button onClick={()=>db.auth.signOut()}>Esci</button>}</aside><main><header><div><p className="eyebrow">IL VOSTRO QUOTIDIANO, IN NUMERI</p><h1>{tab}</h1></div><button onClick={()=>setTab('Aggiungi')}>+ Nuova spesa</button></header>{!db&&<div className="notice">Modalità dimostrativa: i dati rimangono solo in memoria e si cancellano ricaricando la pagina. Collega Supabase per salvare.</div>}<p role="status" aria-live="polite">{message}</p>
 {['Metriche','Movimenti'].includes(tab)&&<section className="filters"><label>Anno<select aria-label="Anno" value={f.from.slice(0,4)===f.to.slice(0,4)?f.from.slice(0,4):''} onChange={e=>e.target.value&&setF({...f,from:`${e.target.value}-01-01`,to:`${e.target.value}-12-31`})}><option value="">Intervallo</option>{[...new Set([String(year),...rows.map(r=>r.date.slice(0,4))])].sort().reverse().map(y=><option key={y}>{y}</option>)}</select></label><label>Dal<input type="date" value={f.from} max={f.to} onChange={e=>pick('from',e.target.value)}/></label><label>Al<input type="date" value={f.to} min={f.from} onChange={e=>pick('to',e.target.value)}/></label>{select('Persona','person')}{select('Conto','account')}{select('Categoria','category')}<label>Ambito<select aria-label="Ambito" value={f.scope} onChange={e=>pick('scope',e.target.value)}><option value="">Tutti</option><option value="shared">Condivise</option><option value="personal">Personali</option></select></label><div className="shortcuts">{[30,90,365].map(d=><button key={d} className="subtle" onClick={()=>setF({...f,from:new Date(Date.now()-(d-1)*86400000).toISOString().slice(0,10),to:today})}>Ultimi {d} giorni</button>)}<button className="subtle" onClick={()=>setF({...f,from:`${year}-01-01`,to:today})}>Da inizio anno</button></div></section>}
 {tab==='Metriche'&&!rangeValid&&<p role="alert">Seleziona un intervallo valido: la data iniziale deve precedere o coincidere con quella finale.</p>}
 {tab==='Metriche'&&rangeValid&&<><div className="cards">{[['Entrate',m.income],['Spese nette',m.spending],['Risparmio',m.saving],['Investimenti',m.investments]].map(([label,value])=><article key={label}><p>{label}</p><strong>{euro(value)}</strong></article>)}</div><p>Tasso di risparmio: <b>{m.rate===null?'Non disponibile':`${(m.rate*100).toFixed(1)}%`}</b> · {filtered.length} movimenti nel periodo</p><div className="grid"><section className="panel"><h2>Spese per categoria</h2>{Object.entries(m.categories).sort((a,b)=>b[1]-a[1]).map(([c,v])=><button className="barrow" key={c} onClick={()=>{pick('category',c);setTab('Movimenti');}}><span>{c}</span><b>{euro(v)}</b><i style={{width:`${Math.max(0,v)/Math.max(1,...Object.values(m.categories))*100}%`}}/></button>)}{!Object.keys(m.categories).length&&<p>Nessuna spesa registrata in questo intervallo.</p>}</section><section className="panel"><h2>Andamento mensile</h2><div className="tablewrap"><table><thead><tr><th>Mese</th><th>Entrate</th><th>Spese</th></tr></thead><tbody>{Object.entries(m.months).sort().map(([month,v])=><tr key={month}><td>{month}</td><td>{euro(v.income)}</td><td>{euro(v.spending)}</td></tr>)}</tbody></table></div></section></div><section className="panel"><h2>Confronto con il periodo precedente</h2><p>Intervallo di uguale durata: {previousPeriod(f.from,f.to).from} — {previousPeriod(f.from,f.to).to}</p><p>Spese registrate: {euro(prev.spending)} · Differenza: {euro(m.spending-prev.spending)}</p><small>La copertura degli import non è verificata. Un periodo vuoto non implica assenza di spese. Risparmio = entrate − spese nette, prima degli investimenti.</small></section></>}
 {tab==='Movimenti'&&<section className="panel"><button className="subtle" onClick={()=>{const blob=new Blob([JSON.stringify(rows,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='note-spese-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Esporta tutti i dati JSON</button><div className="tablewrap"><table><thead><tr>{['Data','Descrizione','Persona / conto','Categoria','Importo',''].map((x,i)=><th key={i}>{x}</th>)}</tr></thead><tbody>{filtered.sort((a,b)=>b.date.localeCompare(a.date)).map(r=><tr key={r.id}><td>{r.date}</td><td>{r.description}{r.shared&&<small>Condivisa</small>}</td><td>{r.person}<small>{r.account}</small></td><td>{r.category}</td><td className={r.amount>0?'positive':''}>{euro(r.amount)}</td><td><button className="subtle" disabled={busy} onClick={()=>{if(confirm('Eliminare questo movimento?'))run(async()=>{if(db)await removeExpenses([r.id]);setRows(rows.filter(x=>x.id!==r.id));});}}>Elimina</button></td></tr>)}</tbody></table>{!filtered.length&&<p>Nessun movimento nel periodo selezionato.</p>}</div></section>}
 {tab==='Aggiungi'&&<section className="panel"><h2>Registra un movimento</h2><form className="entry" onSubmit={e=>{e.preventDefault();run(async()=>{const amount=Math.abs(cents(form.amount))*(['expense','investment'].includes(form.kind)?-1:1);await persist([validate({...form,amount,id:crypto.randomUUID()})]);setMessage('Movimento salvato');setForm({...form,description:'',amount:''});});}}>{[['Data','date','date'],['Descrizione','description','text'],['Importo €','amount','text'],['Persona','person','text'],['Conto','account','text'],['Categoria','category','text']].map(([label,key,type])=><label key={key}>{label}<input required type={type} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Tipo<select aria-label="Tipo" value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}>{Object.entries({expense:'Spesa',income:'Entrata',refund:'Rimborso',investment:'Investimento',transfer:'Trasferimento',opening:'Saldo iniziale'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="check"><input type="checkbox" checked={form.shared} onChange={e=>setForm({...form,shared:e.target.checked})}/>Spesa condivisa</label><button disabled={busy}>Salva movimento</button></form></section>}
 {tab==='Importa'&&<section className="panel"><h2>Importa da Excel</h2><p>Carica un file .xlsx. Seleziona il foglio e associa le colonne, quindi controlla l’anteprima. I PDF saranno supportati in una fase successiva.</p><input aria-label="File Excel" type="file" accept=".xlsx" disabled={busy} onChange={e=>upload(e.target.files[0])}/>{sheets.length>0&&<><div className="entry"><label>Foglio<select aria-label="Foglio" value={sheet} onChange={e=>{setSheet(Number(e.target.value));setPreview(null);}}>{sheets.map((s,i)=><option value={i} key={i}>{s.name}</option>)}</select></label>{Object.entries({date:'Data',description:'Descrizione',amount:'Importo',person:'Persona',account:'Conto',category:'Categoria',shared:'Condivisa'}).map(([k,label])=><label key={k}>{label}<select aria-label={label} value={map[k]} onChange={e=>{setMap({...map,[k]:Number(e.target.value)});setPreview(null);}}><option value={-1}>Non presente</option>{(sheets[sheet].rows[0]||[]).map((v,i)=><option value={i} key={i}>{String(v||`Colonna ${i+1}`)}</option>)}</select></label>)}{['person','account'].map(k=><label key={k}>{k==='person'?'Persona predefinita':'Conto predefinito'}<input value={defaults[k]} onChange={e=>{setDefaults({...defaults,[k]:e.target.value});setPreview(null);}}/></label>)}</div><button onClick={prepare}>Prepara anteprima</button></>}{preview&&<><h2>{preview.result.length} righe valide · {preview.errors.length} da correggere</h2>{preview.errors.length>0&&<details><summary>Righe escluse: correggi il file per importarle</summary>{preview.errors.map((e,i)=><p key={i}>{e}</p>)}</details>}<p>I possibili duplicati sono deselezionati. Puoi includerli se sono acquisti distinti.</p><div className="tablewrap"><table><thead><tr><th>Importa</th><th>Data</th><th>Descrizione</th><th>Categoria</th><th>Importo</th></tr></thead><tbody>{preview.result.map(r=><tr key={r.id}><td><input aria-label={`Importa ${r.description}`} type="checkbox" checked={chosen.has(r.id)} onChange={e=>{const n=new Set(chosen);e.target.checked?n.add(r.id):n.delete(r.id);setChosen(n);}}/>{r.duplicate&&'Possibile duplicato'}</td><td>{r.date}</td><td>{r.description}</td><td>{r.category}</td><td>{euro(r.amount)}</td></tr>)}</tbody></table></div><button disabled={busy||!chosen.size} onClick={()=>run(async()=>{const batch=crypto.randomUUID();await persist(preview.result.filter(r=>chosen.has(r.id)).map(({duplicate,...r})=>({...r,batch})));setPreview(null);setSheets([]);setMessage('Importazione completata');})}>Conferma {chosen.size} movimenti</button></>}{rows.some(r=>r.batch)&&<div><h2>Importazioni</h2>{[...new Set(rows.map(r=>r.batch).filter(Boolean))].map((b,i)=><button className="subtle" key={b} disabled={busy} onClick={()=>{if(confirm('Annullare questo lotto di importazione?'))run(async()=>{const ids=rows.filter(r=>r.batch===b).map(r=>r.id);if(db)await removeExpenses(ids);setRows(rows.filter(r=>r.batch!==b));});}}>Annulla lotto {i+1} ({rows.filter(r=>r.batch===b).length} movimenti)</button>)}</div>}</section>}
 </main></>;
}
createRoot(document.getElementById('root')).render(<App/>);
